<?php

return [
    'label'            => __( 'Homepage Text Block', 'proxima' ),
    'key'              => basename( __DIR__ ),

    /**/
    'tab_demo_preview' => [
        'key'       => 'field_auto_key', // $section->field_auto_key(),
        'type'      => 'message',
        'message'   => 'Homepage Text Block', // marck_section_demo_preview( $section->key ),
        'new_lines' => 'wpautop',
        'esc_html'  => 0,
    ],

    'tab_content' => [

        [
            'key'               => 'field_auto_key',
            'label'             => 'title',
            'name'              => 'title',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'default_value'     => '',
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
            'maxlength'         => '',
        ],
        [
            'key'               => 'field_auto_key',
            'label'             => 'block',
            'name'              => 'block',
            'type'              => 'group',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'layout'            => 'block',
            'sub_fields'        => [
                [
                    'key'               => 'field_auto_key',
                    'label'             => 'title',
                    'name'              => 'title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_auto_key',
                    'label'             => 'content',
                    'name'              => 'content',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ],
                [
                    'key'               => 'field_auto_key',
                    'label'             => 'btn',
                    'name'              => 'btn',
                    'type'              => 'link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'return_format'     => 'array',
                ],
            ],
        ],
        [
            'key'               => 'field_auto_key',
            'label'             => 'image',
            'name'              => 'image',
            'type'              => 'image',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '49',
                'class' => '',
                'id'    => '',
            ],
            'return_format'     => 'id',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'min_width'         => '',
            'min_height'        => '',
            'min_size'          => '',
            'max_width'         => '',
            'max_height'        => '',
            'max_size'          => '',
            'mime_types'        => '',
        ],
        [
            'key'               => 'field_auto_key',
            'label'             => 'Side',
            'name'              => 'side',
            'type'              => 'radio',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '49',
                'class' => '',
                'id'    => '',
            ],
            'choices'           => [
                'left'  => 'Left',
                'right' => 'Right',
            ],
            'allow_null'        => 0,
            'other_choice'      => 0,
            'default_value'     => '',
            'layout'            => 'vertical',
            'return_format'     => 'value',
            'save_other_choice' => 0,
        ],

    ],

    'tab_options' => [],
    /**/
];
