<?php

return [
    'label'            => __( 'Hello Block', 'proxima' ),
    'key'              => basename( __DIR__ ),
    'tab_demo_preview' => [
        'key'       => 'field_auto_key', // $section->field_auto_key(),
        'type'      => 'message',
        'message'   => 'Hello Block', // marck_section_demo_preview( $section->key ),
        'new_lines' => 'wpautop',
        'esc_html'  => 0,
    ],

    'tab_content' => [
        array(
            'key' => 'field_661b46a46ca07',
            'label' => 'Block type',
            'name' => 'block_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'type_1' => 'Type 1',
                'type_2' => 'Type 2',
                'type_3' => 'Type 3',
                'type_4' => 'Type 4',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_661b46f46ca08',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'visual',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),

        array(
            'key' => 'field_661b471b6ca09',
            'label' => 'Background',
            'name' => 'bg',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_662bb453bf106',
            'label' => 'Text',
            'name' => 'text',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_1',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_4',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'visual',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_661b477b6ca0b',
            'label' => 'Link',
            'name' => 'link',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_1',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_2',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_4',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_661b496dcdffc',
            'label' => 'Link Icon',
            'name' => 'icon',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_1',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_2',
                    ),
                ),
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_4',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'id',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_661b47d06ca0c',
            'label' => 'Items',
            'name' => 'items',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_2',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 3,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_661b47e46ca0d',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 5,
                    'new_lines' => 'br',
                ),
            ),
        ),
        array(
            'key' => 'field_661b482c6ca0f',
            'label' => 'Subtitle',
            'name' => 'subtitle',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_3',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_661b484b6ca10',
            'label' => 'Text',
            'name' => 'type_3_text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_3',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_661b485b6ca11',
            'label' => 'Label',
            'name' => 'label',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_3',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_662d1166ae846',
            'label' => 'E-mail',
            'name' => 'email',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_3',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_661b48f8cdff7',
            'label' => 'Items (type 4)',
            'name' => 'items_type_4',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_661b46a46ca07',
                        'operator' => '==',
                        'value' => 'type_4',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 6,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_661b4915cdff8',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_661b4921cdff9',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 2,
                    'new_lines' => '',
                ),
            ),
        ),
    ],

    'tab_options' => [],
    /**/
];
